apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-container
        image: asia-southeast1-docker.pkg.dev/jarkom-adrian/tk-kowan/tk-kowan:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: postgresql://$DATABASE_USER:$DATABASE_PASSWORD@127.0.0.1:5432/$DATABASE_NAME
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        command: ["sh", "-c"]
        args:
          - |
            python manage.py migrate
            gunicorn --bind 0.0.0.0:8000 notes_backend.wsgi:application
      - image: gcr.io/cloudsql-docker/gce-proxy:1.16
        name: cloudsql-proxy
        command:
          - "/bin/sh"
          - "-c"
          - |
            wget -O /cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
            chmod +x /cloud_sql_proxy
            /cloud_sql_proxy -instances=jarkom-adrian:asia-southeast1:postgres=tcp:5432 -credential_file=/secrets/cloudsql/credentials.json
        securityContext:
          runAsUser: 2  # non-root user
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
